version: '3.8'

services:
  postgres:
    image: postgres
    container_name: query-monitoring-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
  redis:
    container_name: query-monitoring-cache
    image: "redis:6.2-alpine"
    restart: unless-stopped
    ports:
      - '6379:6379'
  query-monitoring:
    container_name: query-monitoring
    build: ./
    environment:
      SERVICE_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - default

volumes:
  data: