// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/Javanshir-SH/query-monitoring/internal/todo/service"
	"github.com/Javanshir-SH/query-monitoring/internal/todo/storage"
	"sync"
)

// Ensure, that MockTaskRepository does implement service.TaskRepository.
// If this is not the case, regenerate this file with moq.
var _ service.TaskRepository = &MockTaskRepository{}

// MockTaskRepository is a mock implementation of service.TaskRepository.
//
// 	func TestSomethingThatUsesTaskRepository(t *testing.T) {
//
// 		// make and configure a mocked service.TaskRepository
// 		mockedTaskRepository := &MockTaskRepository{
// 			CreateFunc: func(t storage.Task) error {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(cn storage.Task) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(t storage.Task) (*storage.Task, error) {
// 				panic("mock out the Get method")
// 			},
// 			UpdateFunc: func(cn storage.Task) error {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedTaskRepository in code that requires service.TaskRepository
// 		// and then make assertions.
//
// 	}
type MockTaskRepository struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(t storage.Task) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(cn storage.Task) error

	// GetFunc mocks the Get method.
	GetFunc func(t storage.Task) (*storage.Task, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(cn storage.Task) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// T is the t argument value.
			T storage.Task
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Cn is the cn argument value.
			Cn storage.Task
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// T is the t argument value.
			T storage.Task
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Cn is the cn argument value.
			Cn storage.Task
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *MockTaskRepository) Create(t storage.Task) error {
	if mock.CreateFunc == nil {
		panic("MockTaskRepository.CreateFunc: method is nil but TaskRepository.Create was just called")
	}
	callInfo := struct {
		T storage.Task
	}{
		T: t,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(t)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedTaskRepository.CreateCalls())
func (mock *MockTaskRepository) CreateCalls() []struct {
	T storage.Task
} {
	var calls []struct {
		T storage.Task
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *MockTaskRepository) Delete(cn storage.Task) error {
	if mock.DeleteFunc == nil {
		panic("MockTaskRepository.DeleteFunc: method is nil but TaskRepository.Delete was just called")
	}
	callInfo := struct {
		Cn storage.Task
	}{
		Cn: cn,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(cn)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedTaskRepository.DeleteCalls())
func (mock *MockTaskRepository) DeleteCalls() []struct {
	Cn storage.Task
} {
	var calls []struct {
		Cn storage.Task
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MockTaskRepository) Get(t storage.Task) (*storage.Task, error) {
	if mock.GetFunc == nil {
		panic("MockTaskRepository.GetFunc: method is nil but TaskRepository.Get was just called")
	}
	callInfo := struct {
		T storage.Task
	}{
		T: t,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(t)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedTaskRepository.GetCalls())
func (mock *MockTaskRepository) GetCalls() []struct {
	T storage.Task
} {
	var calls []struct {
		T storage.Task
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *MockTaskRepository) Update(cn storage.Task) error {
	if mock.UpdateFunc == nil {
		panic("MockTaskRepository.UpdateFunc: method is nil but TaskRepository.Update was just called")
	}
	callInfo := struct {
		Cn storage.Task
	}{
		Cn: cn,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(cn)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedTaskRepository.UpdateCalls())
func (mock *MockTaskRepository) UpdateCalls() []struct {
	Cn storage.Task
} {
	var calls []struct {
		Cn storage.Task
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
